# 集群，只是端口不一样
#server:
#  port: 8001

spring:
  profiles: dev001
  application:
    name: order-server
---
server:
  port: 8001

spring:
  profiles: dev001
  application:
    name: microservice-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/shoppingMall?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:  # 连接池设置
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间

# mybatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  # 所有entity别名类所在包路径（实体类）,使得在mapper.xml里不需要写全类名。resultMap的type或者parameterType会使用自定义的pojo
  type-aliases-package: com.weigq.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件所在路径


# 注册中心配置
eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:
      # # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      # 单击版
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群版  配置其他的Eureka Server服务端访问地址，有多个注册中心，用逗号隔开（这里是三台注册注册中心）
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    prefer-ip-address: true # 访问路径可以显示IP地址

# 开启feign自带的 熔断器功能
feign:
  hystrix:
    enabled: true
---
server:
  port: 8002

spring:
  profiles: dev002
  application:
    name: microservice-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/shoppingMall?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:  # 连接池设置
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间

# mybatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径 mybatis/mybatis.cfg.xml
  # 所有entity别名类所在包路径（实体类）,使得在mapper.xml里不需要写全类名。resultMap的type或者parameterType会使用自定义的pojo
  type-aliases-package: com.weigq.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件所在路径


# 注册中心配置
eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:
      # # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      # 单击版
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群版  配置其他的Eureka Server服务端访问地址，有多个注册中心，用逗号隔开（这里是三台注册注册中心）
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    prefer-ip-address: true # 访问路径可以显示IP地址

# 开启feign自带的 熔断器功能
feign:
  hystrix:
    enabled: true